name: soulnotes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png

flutter_native_splash:
  color: "#FFFFFF"             # white background
  image: assets/splash_logo.png
  ios_content_mode: center     # keeps logo centered
  android_gravity: center      # centers on Android
  android_12:
    image: assets/splash_logo.png
    color: "#FFFFFF"