name: soulnotes
description: "SoulNotes app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  change_app_package_name: ^1.5.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sn_splash_cover.png      # iOS in-app splash
    - assets/splash_logo2.png         # square logo (iOS + Android <12)
    - assets/splash_1080.png
    - assets/flowers.png
    - assets/candle.png          

flutter_native_splash:
  color: "#FFFFFF"

  # iOS & Android < 12: centered square logo
  image: assets/splash_logo2.png
  ios_content_mode: scaleAspectFit
  android_gravity: center

  # Android 12+: background only (no circle mask)
  android_12:
    background_image: assets/splash_1080.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    branding: false





